serializing bigint
angular-architects/ngrx-toolkit pull request #31
Opened 2024-04-06 17:22 UTC by robmanganelly

Content of this PR:
- 2 Functions that wrap JSON.stringify and JSON.parse to include serialization and rehydration of bigint values. 
- Unit test code modifications to include values of type bigint on test cases.

Considerations.
- I applied the functions in place for the sake of brevity, but next iterations could move them into utility space and get them their own unit test.
- There is a commented test case, see line 137 that has failing test case, which i did not fix, as it is a different issue, unrelated to this PR.

2024-04-14 18:17 UTC, rainerhahnekamp requested changes
Good work @robmanganelly. I've left some comments.

2024-04-14 18:17 UTC, rainerhahnekamp commented on libs/ngrx-toolkit/src/lib/with-storage-sync.spec.ts
> +import { withBigIntRehydration, withBigIntReplacement, withStorageSync } from './with-storage-sync';
Would it be possible to rename `withBigIntRehydration` and `withBigIntReplacement` to `serialize` and `deserialize`. I think `bigint` will not be the last type where we require custom code.

2024-04-14 18:17 UTC, rainerhahnekamp commented on libs/ngrx-toolkit/src/lib/with-storage-sync.spec.ts
> +  big: bigint;
Would it be possible, that we leave the tests as they are and just create a separate test which checks the de/serialization for `bigint`?

2024-04-14 18:17 UTC, rainerhahnekamp commented on package-lock.json
I don't think that the `package-lock.json` should be changed, right?

2024-04-14 18:17 UTC, rainerhahnekamp commented on libs/ngrx-toolkit/src/lib/with-storage-sync.ts
> +   * ~~`JSON.parse()` by default~~
Yes, you can replace that with `parse` and `stringify` (below).

2024-04-25 15:53 UTC, robmanganelly commented
Sorry for the late reply. Yes. I will take care of it. Thanks for the
comments.

On Sun, Apr 14, 2024, 14:17 Rainer Hahnekamp ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> Good work @robmanganelly <https://github.com/robmanganelly>. I've left
> some comments.
> ------------------------------
>
> In libs/ngrx-toolkit/src/lib/with-storage-sync.spec.ts
> <https://github.com/angular-architects/ngrx-toolkit/pull/31#discussion_r1564854837>
> :
>
> > @@ -1,14 +1,16 @@
>  import { getState, patchState, signalStore, withState } from ***@***.***/signals';
> -import { withStorageSync } from './with-storage-sync';
> +import { withBigIntRehydration, withBigIntReplacement, withStorageSync } from './with-storage-sync';
>
> Would it be possible to rename withBigIntRehydration and
> withBigIntReplacement to serialize and deserialize. I think bigint will
> not be the last type where we require custom code.
> ------------------------------
>
> In libs/ngrx-toolkit/src/lib/with-storage-sync.spec.ts
> <https://github.com/angular-architects/ngrx-toolkit/pull/31#discussion_r1564856064>
> :
>
> >  import { TestBed } from ***@***.***/core/testing';
>
>  interface StateObject {
>    foo: string;
>    age: number;
> +  big: bigint;
>
> Would it be possible, that we leave the tests as they are and just create
> a separate test which checks the de/serialization for bigint?
> ------------------------------
>
> On package-lock.json
> <https://github.com/angular-architects/ngrx-toolkit/pull/31#discussion_r1564857445>
> :
>
> I don't think that the package-lock.json should be changed, right?
> ------------------------------
>
> In libs/ngrx-toolkit/src/lib/with-storage-sync.ts
> <https://github.com/angular-architects/ngrx-toolkit/pull/31#discussion_r1564859762>
> :
>
> > @@ -58,15 +104,20 @@ export type SyncConfig<State> = {
>    /**
>     * Function used to parse the state coming from storage.
>     *
> -   * `JSON.parse()` by default
> +   * ~~`JSON.parse()` by default~~
>
> Yes, you can replace that with parse and stringify (below).
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/angular-architects/ngrx-toolkit/pull/31#pullrequestreview-1999723011>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AWTAHEL5JTHL7NVGJ2BSCULY5LB4NAVCNFSM6AAAAABF2S4TJKVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTSOJZG4ZDGMBRGE>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-04-25 16:10 UTC, rainerhahnekamp commented
@robmanganelly if you don't have the time, no worries. We'll merge and I can do the changes myself. Just let me know, cheers!

2024-04-25 20:01 UTC, robmanganelly commented
Honestly, I don't want to pass the workload onto you guys. I'm really happy
to contribute to this project, even if my contributions are minuscule, but
I currently don't have the bandwidth, sadly, for which I apologize.
 I can reach out once I'm done with my current tasks, and if changes are
still needed, I'll be more than happy to handle them myself.

Otherwise, please proceed as you see fit.

2025-08-10 17:49 UTC, closed without merging